name: Deploy Flutter Web App to GitHub Pages

on:
  push:
    branches:
      - main  # 또는 Flutter 앱의 소스 코드가 있는 브랜치 이름

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1

    - name: Setup Flutter
      uses: subosito/flutter-action@v2.12.0
      with:
        flutter-version: '3.16.3' # 사용하는 Flutter 버전으로 변경
    
    - run: flutter pub get

    - run: flutter config --enable-web
    - run: flutter build web --base-href "/${{ github.event.repository.name }}/"
    
    - run: git config user.name github-actions
    - run: git config user.email github-actions@github.com
    - run: git --work-tree build/web add --all
    - run: git commit -m "Automatic deployment by github-actions"
    - run: git push origin HEAD:gh_pages --force